version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - mentorship-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
